
language: node_js
node_js:
- 9.2.1

install: 
- ./install-tools.sh
- ./install-modules.sh
- ./link-all.sh

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: 
- npm run cover
- npm run test-apps  

after_script:
  - ./auto-publish.sh
  - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT
